sudo apt-get install python-pip;
sudo pip install numpy;
sudo pip install python-dev python-devel;
sudo pip install matplotlib;
sudo pip install png;
sudo pip install freetype;
sudo pip install matplotlib;
sudo pip install scipy;
sudo pip install sklearn;
sudo pip install -U scikit-learn;
